apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minio/minio.git
    targetRevision: HEAD
    path: helm/minio
  destination:
    namespace: default
    name: in-cluster