apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: HEAD
    path: bitnami/postgresql